db = db.getSiblingDB('proyecto_bases');

db.createCollection('ecommerce');


db.ecommerce.insertMany([{'id_producto': 'PROD1000',
'nombre': 'Sony Controller',
'precio': 959.83,
'marca': 'Sony',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 4.52},
{'id_producto': 'PROD1001',
'nombre': 'Sony Controller',
'precio': 787.3,
'marca': 'Sony',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 4.38},
{'id_producto': 'PROD1002',
'nombre': 'Sony Console',
'precio': 109.5,
'marca': 'Sony',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 3.84},
{'id_producto': 'PROD1003',
'nombre': 'Sony Game',
'precio': 836.99,
'marca': 'Sony',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 1.24},
{'id_producto': 'PROD1004',
'nombre': 'Sony Headset',
'precio': 826.28,
'marca': 'Sony',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 1.47},
{'id_producto': 'PROD1005',
'nombre': 'Sony Headset',
'precio': 14.12,
'marca': 'Sony',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 3.55},
{'id_producto': 'PROD1006',
'nombre': 'Sony VR Headset',
'precio': 642.01,
'marca': 'Sony',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 1.25},
{'id_producto': 'PROD1007',
'nombre': 'Sony Controller',
'precio': 424.27,
'marca': 'Sony',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 1.34},
{'id_producto': 'PROD1008',
'nombre': 'Sony VR Headset',
'precio': 757.55,
'marca': 'Sony',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 2.56},
{'id_producto': 'PROD1009',
'nombre': 'Sony Headset',
'precio': 420.95,
'marca': 'Sony',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 1.98},
{'id_producto': 'PROD1010',
'nombre': 'Sony VR Headset',
'precio': 52.8,
'marca': 'Sony',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 2.67},
{'id_producto': 'PROD1011',
'nombre': 'Sony Console',
'precio': 691.79,
'marca': 'Sony',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 3.37},
{'id_producto': 'PROD1012',
'nombre': 'Sony Controller',
'precio': 299.47,
'marca': 'Sony',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 1.45},
{'id_producto': 'PROD1013',
'nombre': 'Sony Headset',
'precio': 341.2,
'marca': 'Sony',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 3.05},
{'id_producto': 'PROD1014',
'nombre': 'Microsoft Console',
'precio': 638.46,
'marca': 'Microsoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 4.64},
{'id_producto': 'PROD1015',
'nombre': 'Microsoft Console',
'precio': 570.46,
'marca': 'Microsoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 4.57},
{'id_producto': 'PROD1016',
'nombre': 'Microsoft Controller',
'precio': 115.21,
'marca': 'Microsoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 2.59},
{'id_producto': 'PROD1017',
'nombre': 'Microsoft Console',
'precio': 639.71,
'marca': 'Microsoft',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 1.2},
{'id_producto': 'PROD1018',
'nombre': 'Microsoft VR Headset',
'precio': 726.48,
'marca': 'Microsoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 2.69},
{'id_producto': 'PROD1019',
'nombre': 'Microsoft VR Headset',
'precio': 887.05,
'marca': 'Microsoft',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 4.22},
{'id_producto': 'PROD1020',
'nombre': 'Microsoft Game',
'precio': 270.73,
'marca': 'Microsoft',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 3.13},
{'id_producto': 'PROD1021',
'nombre': 'Microsoft Game',
'precio': 360.33,
'marca': 'Microsoft',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 4.77},
{'id_producto': 'PROD1022',
'nombre': 'Nintendo Console',
'precio': 314.41,
'marca': 'Nintendo',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 2.29},
{'id_producto': 'PROD1023',
'nombre': 'Nintendo Console',
'precio': 320.02,
'marca': 'Nintendo',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 2.42},
{'id_producto': 'PROD1024',
'nombre': 'Nintendo Headset',
'precio': 219.36,
'marca': 'Nintendo',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 4.32},
{'id_producto': 'PROD1025',
'nombre': 'Nintendo Console',
'precio': 70.63,
'marca': 'Nintendo',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 4.16},
{'id_producto': 'PROD1026',
'nombre': 'Nintendo Controller',
'precio': 718.51,
'marca': 'Nintendo',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 3.97},
{'id_producto': 'PROD1027',
'nombre': 'Nintendo Headset',
'precio': 750.78,
'marca': 'Nintendo',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 4.31},
{'id_producto': 'PROD1028',
'nombre': 'Nintendo Game',
'precio': 155.54,
'marca': 'Nintendo',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 1.47},
{'id_producto': 'PROD1029',
'nombre': 'Nintendo Controller',
'precio': 342.42,
'marca': 'Nintendo',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 4.78},
{'id_producto': 'PROD1030',
'nombre': 'Nintendo Game',
'precio': 378.84,
'marca': 'Nintendo',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 1.84},
{'id_producto': 'PROD1031',
'nombre': 'Ubisoft Controller',
'precio': 47.55,
'marca': 'Ubisoft',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 2.4},
{'id_producto': 'PROD1032',
'nombre': 'Ubisoft Controller',
'precio': 299.05,
'marca': 'Ubisoft',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 2.39},
{'id_producto': 'PROD1033',
'nombre': 'Ubisoft Game',
'precio': 123.19,
'marca': 'Ubisoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 4.5},
{'id_producto': 'PROD1034',
'nombre': 'Ubisoft Game',
'precio': 830.0,
'marca': 'Ubisoft',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 2.52},
{'id_producto': 'PROD1035',
'nombre': 'Ubisoft Headset',
'precio': 428.77,
'marca': 'Ubisoft',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 4.27},
{'id_producto': 'PROD1036',
'nombre': 'Ubisoft Controller',
'precio': 430.02,
'marca': 'Ubisoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 3.01},
{'id_producto': 'PROD1037',
'nombre': 'Ubisoft Game',
'precio': 353.22,
'marca': 'Ubisoft',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 1.45},
{'id_producto': 'PROD1038',
'nombre': 'Ubisoft Console',
'precio': 573.72,
'marca': 'Ubisoft',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 4.42},
{'id_producto': 'PROD1039',
'nombre': 'Ubisoft VR Headset',
'precio': 877.31,
'marca': 'Ubisoft',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 1.51},
{'id_producto': 'PROD1040',
'nombre': 'Ubisoft Headset',
'precio': 168.09,
'marca': 'Ubisoft',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 2.21},
{'id_producto': 'PROD1041',
'nombre': 'Ubisoft Controller',
'precio': 975.03,
'marca': 'Ubisoft',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 1.85},
{'id_producto': 'PROD1042',
'nombre': 'Ubisoft VR Headset',
'precio': 31.91,
'marca': 'Ubisoft',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 4.64},
{'id_producto': 'PROD1043',
'nombre': 'Ubisoft Console',
'precio': 617.95,
'marca': 'Ubisoft',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 4.71},
{'id_producto': 'PROD1044',
'nombre': 'Ubisoft VR Headset',
'precio': 314.51,
'marca': 'Ubisoft',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 3.88},
{'id_producto': 'PROD1045',
'nombre': 'Ubisoft Game',
'precio': 827.06,
'marca': 'Ubisoft',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 1.26},
{'id_producto': 'PROD1046',
'nombre': 'EA VR Headset',
'precio': 425.53,
'marca': 'EA',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 1.56},
{'id_producto': 'PROD1047',
'nombre': 'EA Controller',
'precio': 506.3,
'marca': 'EA',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 1.79},
{'id_producto': 'PROD1048',
'nombre': 'EA Headset',
'precio': 305.71,
'marca': 'EA',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 1.36},
{'id_producto': 'PROD1049',
'nombre': 'EA Console',
'precio': 517.15,
'marca': 'EA',
'pais_fabricacion': 'Germany',
'categoria': 'Videojuegos',
'puntuacion_media': 4.27},
{'id_producto': 'PROD1050',
'nombre': 'EA Headset',
'precio': 849.79,
'marca': 'EA',
'pais_fabricacion': 'Japan',
'categoria': 'Videojuegos',
'puntuacion_media': 2.41},
{'id_producto': 'PROD1051',
'nombre': 'EA Controller',
'precio': 929.93,
'marca': 'EA',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 1.42},
{'id_producto': 'PROD1052',
'nombre': 'EA Headset',
'precio': 180.45,
'marca': 'EA',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 4.58},
{'id_producto': 'PROD1053',
'nombre': 'EA Headset',
'precio': 470.85,
'marca': 'EA',
'pais_fabricacion': 'South Korea',
'categoria': 'Videojuegos',
'puntuacion_media': 4.32},
{'id_producto': 'PROD1054',
'nombre': 'EA Controller',
'precio': 570.25,
'marca': 'EA',
'pais_fabricacion': 'USA',
'categoria': 'Videojuegos',
'puntuacion_media': 1.01},
{'id_producto': 'PROD1055',
'nombre': 'EA Console',
'precio': 245.56,
'marca': 'EA',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 2.9},
{'id_producto': 'PROD1056',
'nombre': 'EA Console',
'precio': 102.98,
'marca': 'EA',
'pais_fabricacion': 'China',
'categoria': 'Videojuegos',
'puntuacion_media': 1.91},
{'id_producto': 'PROD1057',
'nombre': 'EA Headset',
'precio': 756.31,
'marca': 'EA',
'pais_fabricacion': 'India',
'categoria': 'Videojuegos',
'puntuacion_media': 3.27},
{'id_producto': 'PROD1058',
'nombre': 'Apple Charger',
'precio': 486.03,
'marca': 'Apple',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 1.55},
{'id_producto': 'PROD1059',
'nombre': 'Apple Charger',
'precio': 618.82,
'marca': 'Apple',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 2.0},
{'id_producto': 'PROD1060',
'nombre': 'Apple Smartwatch',
'precio': 898.18,
'marca': 'Apple',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.34},
{'id_producto': 'PROD1061',
'nombre': 'Apple Earbuds',
'precio': 664.93,
'marca': 'Apple',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.23},
{'id_producto': 'PROD1062',
'nombre': 'Apple Smartwatch',
'precio': 949.5,
'marca': 'Apple',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 3.29},
{'id_producto': 'PROD1063',
'nombre': 'Apple Earbuds',
'precio': 748.09,
'marca': 'Apple',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 4.12},
{'id_producto': 'PROD1064',
'nombre': 'Apple Charger',
'precio': 366.8,
'marca': 'Apple',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 3.11},
{'id_producto': 'PROD1065',
'nombre': 'Apple Earbuds',
'precio': 746.32,
'marca': 'Apple',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.13},
{'id_producto': 'PROD1066',
'nombre': 'Apple Earbuds',
'precio': 649.98,
'marca': 'Apple',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 4.68},
{'id_producto': 'PROD1067',
'nombre': 'Samsung Charger',
'precio': 473.91,
'marca': 'Samsung',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.09},
{'id_producto': 'PROD1068',
'nombre': 'Samsung Tablet',
'precio': 166.43,
'marca': 'Samsung',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.09},
{'id_producto': 'PROD1069',
'nombre': 'Samsung Tablet',
'precio': 993.38,
'marca': 'Samsung',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 1.16},
{'id_producto': 'PROD1070',
'nombre': 'Samsung Tablet',
'precio': 137.61,
'marca': 'Samsung',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 2.74},
{'id_producto': 'PROD1071',
'nombre': 'Samsung Charger',
'precio': 98.47,
'marca': 'Samsung',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 1.51},
{'id_producto': 'PROD1072',
'nombre': 'Samsung Tablet',
'precio': 190.16,
'marca': 'Samsung',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 2.2},
{'id_producto': 'PROD1073',
'nombre': 'Samsung Smartphone',
'precio': 276.24,
'marca': 'Samsung',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 1.19},
{'id_producto': 'PROD1074',
'nombre': 'Samsung Smartwatch',
'precio': 841.41,
'marca': 'Samsung',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 1.49},
{'id_producto': 'PROD1075',
'nombre': 'Samsung Earbuds',
'precio': 664.16,
'marca': 'Samsung',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 4.99},
{'id_producto': 'PROD1076',
'nombre': 'Samsung Smartwatch',
'precio': 624.72,
'marca': 'Samsung',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 1.08},
{'id_producto': 'PROD1077',
'nombre': 'Samsung Smartwatch',
'precio': 459.35,
'marca': 'Samsung',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 2.91},
{'id_producto': 'PROD1078',
'nombre': 'Huawei Earbuds',
'precio': 33.97,
'marca': 'Huawei',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 2.07},
{'id_producto': 'PROD1079',
'nombre': 'Huawei Earbuds',
'precio': 460.55,
'marca': 'Huawei',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 2.75},
{'id_producto': 'PROD1080',
'nombre': 'Huawei Tablet',
'precio': 544.44,
'marca': 'Huawei',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 3.38},
{'id_producto': 'PROD1081',
'nombre': 'Huawei Tablet',
'precio': 384.02,
'marca': 'Huawei',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 3.42},
{'id_producto': 'PROD1082',
'nombre': 'Huawei Earbuds',
'precio': 408.57,
'marca': 'Huawei',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 2.34},
{'id_producto': 'PROD1083',
'nombre': 'Huawei Tablet',
'precio': 883.44,
'marca': 'Huawei',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 1.64},
{'id_producto': 'PROD1084',
'nombre': 'Huawei Smartwatch',
'precio': 444.9,
'marca': 'Huawei',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 3.85},
{'id_producto': 'PROD1085',
'nombre': 'Huawei Charger',
'precio': 86.04,
'marca': 'Huawei',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 3.39},
{'id_producto': 'PROD1086',
'nombre': 'Huawei Tablet',
'precio': 207.91,
'marca': 'Huawei',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 2.51},
{'id_producto': 'PROD1087',
'nombre': 'Xiaomi Earbuds',
'precio': 168.59,
'marca': 'Xiaomi',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 3.63},
{'id_producto': 'PROD1088',
'nombre': 'Xiaomi Smartphone',
'precio': 846.3,
'marca': 'Xiaomi',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 2.88},
{'id_producto': 'PROD1089',
'nombre': 'Xiaomi Smartphone',
'precio': 935.68,
'marca': 'Xiaomi',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.89},
{'id_producto': 'PROD1090',
'nombre': 'Xiaomi Smartphone',
'precio': 63.9,
'marca': 'Xiaomi',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 2.02},
{'id_producto': 'PROD1091',
'nombre': 'Xiaomi Smartphone',
'precio': 995.84,
'marca': 'Xiaomi',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.35},
{'id_producto': 'PROD1092',
'nombre': 'Xiaomi Tablet',
'precio': 908.3,
'marca': 'Xiaomi',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 4.02},
{'id_producto': 'PROD1093',
'nombre': 'Xiaomi Smartwatch',
'precio': 788.44,
'marca': 'Xiaomi',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 2.7},
{'id_producto': 'PROD1094',
'nombre': 'Xiaomi Smartphone',
'precio': 628.52,
'marca': 'Xiaomi',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 4.24},
{'id_producto': 'PROD1095',
'nombre': 'Xiaomi Earbuds',
'precio': 525.08,
'marca': 'Xiaomi',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.78},
{'id_producto': 'PROD1096',
'nombre': 'Xiaomi Charger',
'precio': 390.98,
'marca': 'Xiaomi',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 2.65},
{'id_producto': 'PROD1097',
'nombre': 'Xiaomi Smartphone',
'precio': 687.69,
'marca': 'Xiaomi',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 4.19},
{'id_producto': 'PROD1098',
'nombre': 'Xiaomi Smartphone',
'precio': 222.4,
'marca': 'Xiaomi',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 1.88},
{'id_producto': 'PROD1099',
'nombre': 'Xiaomi Tablet',
'precio': 91.54,
'marca': 'Xiaomi',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.21},
{'id_producto': 'PROD1100',
'nombre': 'Xiaomi Smartphone',
'precio': 524.52,
'marca': 'Xiaomi',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 4.24},
{'id_producto': 'PROD1101',
'nombre': 'Nokia Smartphone',
'precio': 906.05,
'marca': 'Nokia',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 1.54},
{'id_producto': 'PROD1102',
'nombre': 'Nokia Charger',
'precio': 125.88,
'marca': 'Nokia',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 2.91},
{'id_producto': 'PROD1103',
'nombre': 'Nokia Smartwatch',
'precio': 101.02,
'marca': 'Nokia',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 3.11},
{'id_producto': 'PROD1104',
'nombre': 'Nokia Earbuds',
'precio': 314.45,
'marca': 'Nokia',
'pais_fabricacion': 'India',
'categoria': 'Telefonía',
'puntuacion_media': 4.68},
{'id_producto': 'PROD1105',
'nombre': 'Nokia Charger',
'precio': 97.75,
'marca': 'Nokia',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.37},
{'id_producto': 'PROD1106',
'nombre': 'Nokia Charger',
'precio': 411.01,
'marca': 'Nokia',
'pais_fabricacion': 'Japan',
'categoria': 'Telefonía',
'puntuacion_media': 1.15},
{'id_producto': 'PROD1107',
'nombre': 'Nokia Earbuds',
'precio': 883.64,
'marca': 'Nokia',
'pais_fabricacion': 'USA',
'categoria': 'Telefonía',
'puntuacion_media': 3.83},
{'id_producto': 'PROD1108',
'nombre': 'Nokia Charger',
'precio': 775.89,
'marca': 'Nokia',
'pais_fabricacion': 'South Korea',
'categoria': 'Telefonía',
'puntuacion_media': 3.07},
{'id_producto': 'PROD1109',
'nombre': 'Nokia Earbuds',
'precio': 469.28,
'marca': 'Nokia',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 2.18},
{'id_producto': 'PROD1110',
'nombre': 'Nokia Smartphone',
'precio': 147.8,
'marca': 'Nokia',
'pais_fabricacion': 'Germany',
'categoria': 'Telefonía',
'puntuacion_media': 3.8},
{'id_producto': 'PROD1111',
'nombre': 'Nokia Smartwatch',
'precio': 251.53,
'marca': 'Nokia',
'pais_fabricacion': 'China',
'categoria': 'Telefonía',
'puntuacion_media': 4.17},
{'id_producto': 'PROD1112',
'nombre': 'Optimum Nutrition BCAA',
'precio': 372.4,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.05},
{'id_producto': 'PROD1113',
'nombre': 'Optimum Nutrition Creatine',
'precio': 598.08,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.65},
{'id_producto': 'PROD1114',
'nombre': 'Optimum Nutrition Creatine',
'precio': 176.44,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.67},
{'id_producto': 'PROD1115',
'nombre': 'Optimum Nutrition Creatine',
'precio': 991.7,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.07},
{'id_producto': 'PROD1116',
'nombre': 'Optimum Nutrition Pre-Workout',
'precio': 445.27,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.43},
{'id_producto': 'PROD1117',
'nombre': 'Optimum Nutrition BCAA',
'precio': 475.31,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.24},
{'id_producto': 'PROD1118',
'nombre': 'Optimum Nutrition BCAA',
'precio': 845.42,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.26},
{'id_producto': 'PROD1119',
'nombre': 'Optimum Nutrition Pre-Workout',
'precio': 942.92,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.09},
{'id_producto': 'PROD1120',
'nombre': 'Optimum Nutrition Vitamins',
'precio': 453.51,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.05},
{'id_producto': 'PROD1121',
'nombre': 'Optimum Nutrition Protein Powder',
'precio': 415.02,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.41},
{'id_producto': 'PROD1122',
'nombre': 'Optimum Nutrition Vitamins',
'precio': 293.28,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.52},
{'id_producto': 'PROD1123',
'nombre': 'Optimum Nutrition Pre-Workout',
'precio': 179.89,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.47},
{'id_producto': 'PROD1124',
'nombre': 'Optimum Nutrition Pre-Workout',
'precio': 562.61,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.98},
{'id_producto': 'PROD1125',
'nombre': 'Optimum Nutrition Vitamins',
'precio': 566.03,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.83},
{'id_producto': 'PROD1126',
'nombre': 'Optimum Nutrition Creatine',
'precio': 550.07,
'marca': 'Optimum Nutrition',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.76},
{'id_producto': 'PROD1127',
'nombre': 'MuscleTech Creatine',
'precio': 757.66,
'marca': 'MuscleTech',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.34},
{'id_producto': 'PROD1128',
'nombre': 'MuscleTech BCAA',
'precio': 483.99,
'marca': 'MuscleTech',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.63},
{'id_producto': 'PROD1129',
'nombre': 'MuscleTech Creatine',
'precio': 812.64,
'marca': 'MuscleTech',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.03},
{'id_producto': 'PROD1130',
'nombre': 'MuscleTech Pre-Workout',
'precio': 927.5,
'marca': 'MuscleTech',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.21},
{'id_producto': 'PROD1131',
'nombre': 'MuscleTech BCAA',
'precio': 413.84,
'marca': 'MuscleTech',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.95},
{'id_producto': 'PROD1132',
'nombre': 'MuscleTech BCAA',
'precio': 637.73,
'marca': 'MuscleTech',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.69},
{'id_producto': 'PROD1133',
'nombre': 'MuscleTech Creatine',
'precio': 140.91,
'marca': 'MuscleTech',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.95},
{'id_producto': 'PROD1134',
'nombre': 'MuscleTech Vitamins',
'precio': 293.23,
'marca': 'MuscleTech',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.81},
{'id_producto': 'PROD1135',
'nombre': 'MuscleTech Protein Powder',
'precio': 180.96,
'marca': 'MuscleTech',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.95},
{'id_producto': 'PROD1136',
'nombre': 'MuscleTech Creatine',
'precio': 525.38,
'marca': 'MuscleTech',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.52},
{'id_producto': 'PROD1137',
'nombre': 'Dymatize Creatine',
'precio': 987.05,
'marca': 'Dymatize',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.9},
{'id_producto': 'PROD1138',
'nombre': 'Dymatize BCAA',
'precio': 271.6,
'marca': 'Dymatize',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.52},
{'id_producto': 'PROD1139',
'nombre': 'Dymatize Pre-Workout',
'precio': 869.52,
'marca': 'Dymatize',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.39},
{'id_producto': 'PROD1140',
'nombre': 'Dymatize Pre-Workout',
'precio': 735.08,
'marca': 'Dymatize',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.14},
{'id_producto': 'PROD1141',
'nombre': 'Dymatize Vitamins',
'precio': 73.17,
'marca': 'Dymatize',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.3},
{'id_producto': 'PROD1142',
'nombre': 'Dymatize Protein Powder',
'precio': 316.53,
'marca': 'Dymatize',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.57},
{'id_producto': 'PROD1143',
'nombre': 'Dymatize Creatine',
'precio': 767.68,
'marca': 'Dymatize',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.61},
{'id_producto': 'PROD1144',
'nombre': 'Dymatize BCAA',
'precio': 799.22,
'marca': 'Dymatize',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.77},
{'id_producto': 'PROD1145',
'nombre': 'BSN Creatine',
'precio': 752.24,
'marca': 'BSN',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.12},
{'id_producto': 'PROD1146',
'nombre': 'BSN Creatine',
'precio': 805.97,
'marca': 'BSN',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.95},
{'id_producto': 'PROD1147',
'nombre': 'BSN BCAA',
'precio': 183.25,
'marca': 'BSN',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.19},
{'id_producto': 'PROD1148',
'nombre': 'BSN Creatine',
'precio': 24.11,
'marca': 'BSN',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.87},
{'id_producto': 'PROD1149',
'nombre': 'BSN Protein Powder',
'precio': 845.24,
'marca': 'BSN',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.61},
{'id_producto': 'PROD1150',
'nombre': 'BSN Pre-Workout',
'precio': 110.3,
'marca': 'BSN',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.38},
{'id_producto': 'PROD1151',
'nombre': 'BSN Vitamins',
'precio': 350.09,
'marca': 'BSN',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.28},
{'id_producto': 'PROD1152',
'nombre': 'BSN Pre-Workout',
'precio': 845.36,
'marca': 'BSN',
'pais_fabricacion': 'Germany',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.26},
{'id_producto': 'PROD1153',
'nombre': 'BSN BCAA',
'precio': 516.04,
'marca': 'BSN',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.38},
{'id_producto': 'PROD1154',
'nombre': 'BSN Creatine',
'precio': 33.56,
'marca': 'BSN',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.38},
{'id_producto': 'PROD1155',
'nombre': 'BSN Pre-Workout',
'precio': 591.8,
'marca': 'BSN',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.24},
{'id_producto': 'PROD1156',
'nombre': 'BSN Vitamins',
'precio': 348.92,
'marca': 'BSN',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.04},
{'id_producto': 'PROD1157',
'nombre': 'BSN Pre-Workout',
'precio': 878.34,
'marca': 'BSN',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.8},
{'id_producto': 'PROD1158',
'nombre': 'BSN Vitamins',
'precio': 755.64,
'marca': 'BSN',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.15},
{'id_producto': 'PROD1159',
'nombre': 'GNC Creatine',
'precio': 983.5,
'marca': 'GNC',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.29},
{'id_producto': 'PROD1160',
'nombre': 'GNC Vitamins',
'precio': 640.51,
'marca': 'GNC',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.86},
{'id_producto': 'PROD1161',
'nombre': 'GNC Pre-Workout',
'precio': 571.42,
'marca': 'GNC',
'pais_fabricacion': 'India',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.15},
{'id_producto': 'PROD1162',
'nombre': 'GNC Vitamins',
'precio': 950.23,
'marca': 'GNC',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.3},
{'id_producto': 'PROD1163',
'nombre': 'GNC BCAA',
'precio': 714.82,
'marca': 'GNC',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.5},
{'id_producto': 'PROD1164',
'nombre': 'GNC BCAA',
'precio': 260.79,
'marca': 'GNC',
'pais_fabricacion': 'Japan',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 3.31},
{'id_producto': 'PROD1165',
'nombre': 'GNC BCAA',
'precio': 513.41,
'marca': 'GNC',
'pais_fabricacion': 'USA',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.79},
{'id_producto': 'PROD1166',
'nombre': 'GNC BCAA',
'precio': 100.6,
'marca': 'GNC',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.1},
{'id_producto': 'PROD1167',
'nombre': 'GNC Vitamins',
'precio': 585.03,
'marca': 'GNC',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.61},
{'id_producto': 'PROD1168',
'nombre': 'GNC Protein Powder',
'precio': 343.79,
'marca': 'GNC',
'pais_fabricacion': 'Germany',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 1.05},
{'id_producto': 'PROD1169',
'nombre': 'GNC Creatine',
'precio': 755.15,
'marca': 'GNC',
'pais_fabricacion': 'China',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 4.34},
{'id_producto': 'PROD1170',
'nombre': 'GNC Protein Powder',
'precio': 815.31,
'marca': 'GNC',
'pais_fabricacion': 'South Korea',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.77},
{'id_producto': 'PROD1171',
'nombre': 'GNC Creatine',
'precio': 874.29,
'marca': 'GNC',
'pais_fabricacion': 'Germany',
'categoria': 'Suplementos alimenticios',
'puntuacion_media': 2.7},
{'id_producto': 'PROD1172',
'nombre': 'Nike T-Shirt',
'precio': 149.02,
'marca': 'Nike',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 1.24},
{'id_producto': 'PROD1173',
'nombre': 'Nike T-Shirt',
'precio': 382.41,
'marca': 'Nike',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.02},
{'id_producto': 'PROD1174',
'nombre': 'Nike Shorts',
'precio': 117.84,
'marca': 'Nike',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.29},
{'id_producto': 'PROD1175',
'nombre': 'Nike T-Shirt',
'precio': 47.25,
'marca': 'Nike',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 4.91},
{'id_producto': 'PROD1176',
'nombre': 'Nike Shorts',
'precio': 974.82,
'marca': 'Nike',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 2.64},
{'id_producto': 'PROD1177',
'nombre': 'Nike T-Shirt',
'precio': 669.14,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 3.41},
{'id_producto': 'PROD1178',
'nombre': 'Nike Pants',
'precio': 666.27,
'marca': 'Nike',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 1.47},
{'id_producto': 'PROD1179',
'nombre': 'Nike Pants',
'precio': 343.0,
'marca': 'Nike',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.76},
{'id_producto': 'PROD1180',
'nombre': 'Nike Jacket',
'precio': 680.89,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 2.9},
{'id_producto': 'PROD1181',
'nombre': 'Nike Jacket',
'precio': 732.9,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 2.91},
{'id_producto': 'PROD1182',
'nombre': 'Nike Sweater',
'precio': 728.17,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 3.34},
{'id_producto': 'PROD1183',
'nombre': 'Nike Jacket',
'precio': 77.65,
'marca': 'Nike',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 3.11},
{'id_producto': 'PROD1184',
'nombre': 'Nike Sweater',
'precio': 497.27,
'marca': 'Nike',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 4.84},
{'id_producto': 'PROD1185',
'nombre': 'Nike Sweater',
'precio': 278.12,
'marca': 'Nike',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 2.69},
{'id_producto': 'PROD1186',
'nombre': 'Adidas T-Shirt',
'precio': 821.92,
'marca': 'Adidas',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 2.06},
{'id_producto': 'PROD1187',
'nombre': 'Adidas Shorts',
'precio': 724.99,
'marca': 'Adidas',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 4.62},
{'id_producto': 'PROD1188',
'nombre': 'Adidas Pants',
'precio': 467.01,
'marca': 'Adidas',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 2.22},
{'id_producto': 'PROD1189',
'nombre': 'Adidas Sweater',
'precio': 265.8,
'marca': 'Adidas',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 3.0},
{'id_producto': 'PROD1190',
'nombre': 'Adidas Sweater',
'precio': 271.45,
'marca': 'Adidas',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 2.13},
{'id_producto': 'PROD1191',
'nombre': 'Adidas Shorts',
'precio': 518.55,
'marca': 'Adidas',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 3.72},
{'id_producto': 'PROD1192',
'nombre': 'Adidas Shorts',
'precio': 676.8,
'marca': 'Adidas',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 2.86},
{'id_producto': 'PROD1193',
'nombre': 'Adidas T-Shirt',
'precio': 972.16,
'marca': 'Adidas',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 2.23},
{'id_producto': 'PROD1194',
'nombre': 'Adidas Jacket',
'precio': 49.6,
'marca': 'Adidas',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 2.08},
{'id_producto': 'PROD1195',
'nombre': 'Adidas Sweater',
'precio': 465.58,
'marca': 'Adidas',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 3.52},
{'id_producto': 'PROD1196',
'nombre': 'Puma Pants',
'precio': 163.63,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 2.44},
{'id_producto': 'PROD1197',
'nombre': 'Puma Pants',
'precio': 317.05,
'marca': 'Puma',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 3.04},
{'id_producto': 'PROD1198',
'nombre': 'Puma Sweater',
'precio': 113.8,
'marca': 'Puma',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 1.91},
{'id_producto': 'PROD1199',
'nombre': 'Puma Shorts',
'precio': 884.74,
'marca': 'Puma',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.68},
{'id_producto': 'PROD1200',
'nombre': 'Puma T-Shirt',
'precio': 894.69,
'marca': 'Puma',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 1.27},
{'id_producto': 'PROD1201',
'nombre': 'Puma Jacket',
'precio': 687.78,
'marca': 'Puma',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 3.71},
{'id_producto': 'PROD1202',
'nombre': 'Puma Pants',
'precio': 134.72,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 4.99},
{'id_producto': 'PROD1203',
'nombre': 'Puma Sweater',
'precio': 962.28,
'marca': 'Puma',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 1.89},
{'id_producto': 'PROD1204',
'nombre': 'Puma T-Shirt',
'precio': 364.48,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.09},
{'id_producto': 'PROD1205',
'nombre': 'Puma Shorts',
'precio': 552.16,
'marca': 'Puma',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 3.36},
{'id_producto': 'PROD1206',
'nombre': 'Puma Jacket',
'precio': 430.97,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 4.23},
{'id_producto': 'PROD1207',
'nombre': 'Puma Sweater',
'precio': 600.29,
'marca': 'Puma',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 3.58},
{'id_producto': 'PROD1208',
'nombre': 'Puma Sweater',
'precio': 480.63,
'marca': 'Puma',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 1.38},
{'id_producto': 'PROD1209',
'nombre': 'Puma Jacket',
'precio': 618.28,
'marca': 'Puma',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 4.25},
{'id_producto': 'PROD1210',
'nombre': 'Puma Shorts',
'precio': 812.31,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.17},
{'id_producto': 'PROD1211',
'nombre': 'Under Armour T-Shirt',
'precio': 893.69,
'marca': 'Under Armour',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.03},
{'id_producto': 'PROD1212',
'nombre': 'Under Armour T-Shirt',
'precio': 595.87,
'marca': 'Under Armour',
'pais_fabricacion': 'China',
'categoria': 'Ropa',
'puntuacion_media': 4.0},
{'id_producto': 'PROD1213',
'nombre': 'Under Armour Sweater',
'precio': 284.92,
'marca': 'Under Armour',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 3.69},
{'id_producto': 'PROD1214',
'nombre': 'Under Armour T-Shirt',
'precio': 639.1,
'marca': 'Under Armour',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 1.88},
{'id_producto': 'PROD1215',
'nombre': 'Under Armour Shorts',
'precio': 133.19,
'marca': 'Under Armour',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 3.92},
{'id_producto': 'PROD1216',
'nombre': 'Under Armour Sweater',
'precio': 869.19,
'marca': 'Under Armour',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.01},
{'id_producto': 'PROD1217',
'nombre': 'Under Armour Shorts',
'precio': 321.33,
'marca': 'Under Armour',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 3.55},
{'id_producto': 'PROD1218',
'nombre': 'Under Armour Jacket',
'precio': 284.74,
'marca': 'Under Armour',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 4.57},
{'id_producto': 'PROD1219',
'nombre': 'Under Armour T-Shirt',
'precio': 840.82,
'marca': 'Under Armour',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 1.0},
{'id_producto': 'PROD1220',
'nombre': 'Under Armour T-Shirt',
'precio': 202.52,
'marca': 'Under Armour',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.6},
{'id_producto': 'PROD1221',
'nombre': 'H&M Shorts',
'precio': 647.83,
'marca': 'H&M',
'pais_fabricacion': 'India',
'categoria': 'Ropa',
'puntuacion_media': 2.37},
{'id_producto': 'PROD1222',
'nombre': 'H&M Jacket',
'precio': 909.71,
'marca': 'H&M',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 3.71},
{'id_producto': 'PROD1223',
'nombre': 'H&M Jacket',
'precio': 504.89,
'marca': 'H&M',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.54},
{'id_producto': 'PROD1224',
'nombre': 'H&M Sweater',
'precio': 945.89,
'marca': 'H&M',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 1.71},
{'id_producto': 'PROD1225',
'nombre': 'H&M Jacket',
'precio': 695.86,
'marca': 'H&M',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 4.41},
{'id_producto': 'PROD1226',
'nombre': 'H&M Sweater',
'precio': 495.68,
'marca': 'H&M',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 4.47},
{'id_producto': 'PROD1227',
'nombre': 'H&M Sweater',
'precio': 41.25,
'marca': 'H&M',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 3.65},
{'id_producto': 'PROD1228',
'nombre': 'H&M Pants',
'precio': 591.42,
'marca': 'H&M',
'pais_fabricacion': 'Germany',
'categoria': 'Ropa',
'puntuacion_media': 2.7},
{'id_producto': 'PROD1229',
'nombre': 'H&M T-Shirt',
'precio': 75.85,
'marca': 'H&M',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 4.55},
{'id_producto': 'PROD1230',
'nombre': 'H&M T-Shirt',
'precio': 978.19,
'marca': 'H&M',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 4.1},
{'id_producto': 'PROD1231',
'nombre': 'H&M Pants',
'precio': 436.35,
'marca': 'H&M',
'pais_fabricacion': 'Japan',
'categoria': 'Ropa',
'puntuacion_media': 3.95},
{'id_producto': 'PROD1232',
'nombre': 'H&M Pants',
'precio': 603.5,
'marca': 'H&M',
'pais_fabricacion': 'USA',
'categoria': 'Ropa',
'puntuacion_media': 2.89},
{'id_producto': 'PROD1233',
'nombre': 'H&M T-Shirt',
'precio': 614.24,
'marca': 'H&M',
'pais_fabricacion': 'South Korea',
'categoria': 'Ropa',
'puntuacion_media': 2.39},
{'id_producto': 'PROD1234',
'nombre': "L'Oréal Serum",
'precio': 690.67,
'marca': "L'Oréal",
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 4.95},
{'id_producto': 'PROD1235',
'nombre': "L'Oréal Sunscreen",
'precio': 702.96,
'marca': "L'Oréal",
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.45},
{'id_producto': 'PROD1236',
'nombre': "L'Oréal Serum",
'precio': 17.97,
'marca': "L'Oréal",
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 4.82},
{'id_producto': 'PROD1237',
'nombre': "L'Oréal Toner",
'precio': 212.41,
'marca': "L'Oréal",
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 1.87},
{'id_producto': 'PROD1238',
'nombre': "L'Oréal Cleanser",
'precio': 530.3,
'marca': "L'Oréal",
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 1.85},
{'id_producto': 'PROD1239',
'nombre': "L'Oréal Serum",
'precio': 431.01,
'marca': "L'Oréal",
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 4.36},
{'id_producto': 'PROD1240',
'nombre': "L'Oréal Sunscreen",
'precio': 273.93,
'marca': "L'Oréal",
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 1.13},
{'id_producto': 'PROD1241',
'nombre': "L'Oréal Toner",
'precio': 761.55,
'marca': "L'Oréal",
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.17},
{'id_producto': 'PROD1242',
'nombre': "L'Oréal Sunscreen",
'precio': 817.42,
'marca': "L'Oréal",
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 1.9},
{'id_producto': 'PROD1243',
'nombre': "L'Oréal Serum",
'precio': 880.55,
'marca': "L'Oréal",
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 4.1},
{'id_producto': 'PROD1244',
'nombre': "L'Oréal Cleanser",
'precio': 310.1,
'marca': "L'Oréal",
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 1.49},
{'id_producto': 'PROD1245',
'nombre': "L'Oréal Moisturizer",
'precio': 519.91,
'marca': "L'Oréal",
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 1.3},
{'id_producto': 'PROD1246',
'nombre': "L'Oréal Moisturizer",
'precio': 596.94,
'marca': "L'Oréal",
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 2.39},
{'id_producto': 'PROD1247',
'nombre': "L'Oréal Moisturizer",
'precio': 881.12,
'marca': "L'Oréal",
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 3.41},
{'id_producto': 'PROD1248',
'nombre': 'Neutrogena Moisturizer',
'precio': 311.1,
'marca': 'Neutrogena',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.93},
{'id_producto': 'PROD1249',
'nombre': 'Neutrogena Sunscreen',
'precio': 989.88,
'marca': 'Neutrogena',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 4.93},
{'id_producto': 'PROD1250',
'nombre': 'Neutrogena Toner',
'precio': 716.97,
'marca': 'Neutrogena',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 4.57},
{'id_producto': 'PROD1251',
'nombre': 'Neutrogena Serum',
'precio': 305.11,
'marca': 'Neutrogena',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 4.07},
{'id_producto': 'PROD1252',
'nombre': 'Neutrogena Toner',
'precio': 234.95,
'marca': 'Neutrogena',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 2.52},
{'id_producto': 'PROD1253',
'nombre': 'Neutrogena Serum',
'precio': 996.65,
'marca': 'Neutrogena',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 3.34},
{'id_producto': 'PROD1254',
'nombre': 'Neutrogena Sunscreen',
'precio': 719.54,
'marca': 'Neutrogena',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 1.38},
{'id_producto': 'PROD1255',
'nombre': 'Neutrogena Serum',
'precio': 636.99,
'marca': 'Neutrogena',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 2.83},
{'id_producto': 'PROD1256',
'nombre': 'Neutrogena Sunscreen',
'precio': 304.44,
'marca': 'Neutrogena',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 1.52},
{'id_producto': 'PROD1257',
'nombre': 'Neutrogena Moisturizer',
'precio': 129.15,
'marca': 'Neutrogena',
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 2.36},
{'id_producto': 'PROD1258',
'nombre': 'Neutrogena Sunscreen',
'precio': 302.35,
'marca': 'Neutrogena',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.53},
{'id_producto': 'PROD1259',
'nombre': 'Olay Serum',
'precio': 843.25,
'marca': 'Olay',
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 4.73},
{'id_producto': 'PROD1260',
'nombre': 'Olay Sunscreen',
'precio': 772.78,
'marca': 'Olay',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.43},
{'id_producto': 'PROD1261',
'nombre': 'Olay Moisturizer',
'precio': 644.53,
'marca': 'Olay',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.01},
{'id_producto': 'PROD1262',
'nombre': 'Olay Serum',
'precio': 72.16,
'marca': 'Olay',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 1.63},
{'id_producto': 'PROD1263',
'nombre': 'Olay Toner',
'precio': 279.89,
'marca': 'Olay',
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 4.92},
{'id_producto': 'PROD1264',
'nombre': 'Olay Moisturizer',
'precio': 363.69,
'marca': 'Olay',
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 1.83},
{'id_producto': 'PROD1265',
'nombre': 'Olay Toner',
'precio': 809.74,
'marca': 'Olay',
'pais_fabricacion': 'China',
'categoria': 'Skin Care',
'puntuacion_media': 1.54},
{'id_producto': 'PROD1266',
'nombre': 'Olay Serum',
'precio': 227.89,
'marca': 'Olay',
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 4.33},
{'id_producto': 'PROD1267',
'nombre': 'Clinique Sunscreen',
'precio': 24.64,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.12},
{'id_producto': 'PROD1268',
'nombre': 'Clinique Serum',
'precio': 601.42,
'marca': 'Clinique',
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 2.74},
{'id_producto': 'PROD1269',
'nombre': 'Clinique Sunscreen',
'precio': 655.95,
'marca': 'Clinique',
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 3.57},
{'id_producto': 'PROD1270',
'nombre': 'Clinique Moisturizer',
'precio': 409.11,
'marca': 'Clinique',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 1.45},
{'id_producto': 'PROD1271',
'nombre': 'Clinique Moisturizer',
'precio': 806.36,
'marca': 'Clinique',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 3.95},
{'id_producto': 'PROD1272',
'nombre': 'Clinique Moisturizer',
'precio': 357.22,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.45},
{'id_producto': 'PROD1273',
'nombre': 'Clinique Cleanser',
'precio': 435.65,
'marca': 'Clinique',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.27},
{'id_producto': 'PROD1274',
'nombre': 'Clinique Cleanser',
'precio': 950.95,
'marca': 'Clinique',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 3.44},
{'id_producto': 'PROD1275',
'nombre': 'Clinique Cleanser',
'precio': 144.53,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.48},
{'id_producto': 'PROD1276',
'nombre': 'Clinique Serum',
'precio': 83.98,
'marca': 'Clinique',
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 4.34},
{'id_producto': 'PROD1277',
'nombre': 'Clinique Cleanser',
'precio': 256.49,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 3.27},
{'id_producto': 'PROD1278',
'nombre': 'Clinique Moisturizer',
'precio': 829.22,
'marca': 'Clinique',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 4.08},
{'id_producto': 'PROD1279',
'nombre': 'Clinique Toner',
'precio': 238.59,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 4.55},
{'id_producto': 'PROD1280',
'nombre': 'Clinique Toner',
'precio': 302.23,
'marca': 'Clinique',
'pais_fabricacion': 'Japan',
'categoria': 'Skin Care',
'puntuacion_media': 1.35},
{'id_producto': 'PROD1281',
'nombre': 'Nivea Serum',
'precio': 809.43,
'marca': 'Nivea',
'pais_fabricacion': 'USA',
'categoria': 'Skin Care',
'puntuacion_media': 4.2},
{'id_producto': 'PROD1282',
'nombre': 'Nivea Serum',
'precio': 747.82,
'marca': 'Nivea',
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 2.51},
{'id_producto': 'PROD1283',
'nombre': 'Nivea Serum',
'precio': 115.42,
'marca': 'Nivea',
'pais_fabricacion': 'India',
'categoria': 'Skin Care',
'puntuacion_media': 2.55},
{'id_producto': 'PROD1284',
'nombre': 'Nivea Moisturizer',
'precio': 636.57,
'marca': 'Nivea',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.84},
{'id_producto': 'PROD1285',
'nombre': 'Nivea Cleanser',
'precio': 812.07,
'marca': 'Nivea',
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 3.69},
{'id_producto': 'PROD1286',
'nombre': 'Nivea Cleanser',
'precio': 573.89,
'marca': 'Nivea',
'pais_fabricacion': 'South Korea',
'categoria': 'Skin Care',
'puntuacion_media': 3.5},
{'id_producto': 'PROD1287',
'nombre': 'Nivea Serum',
'precio': 857.52,
'marca': 'Nivea',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.31},
{'id_producto': 'PROD1288',
'nombre': 'Nivea Cleanser',
'precio': 424.54,
'marca': 'Nivea',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 2.61},
{'id_producto': 'PROD1289',
'nombre': 'Nivea Moisturizer',
'precio': 815.19,
'marca': 'Nivea',
'pais_fabricacion': 'Germany',
'categoria': 'Skin Care',
'puntuacion_media': 3.84},
{'id_producto': 'PROD1290',
'nombre': 'Nike Sandals',
'precio': 308.09,
'marca': 'Nike',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 1.03},
{'id_producto': 'PROD1291',
'nombre': 'Nike Boots',
'precio': 228.97,
'marca': 'Nike',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 1.54},
{'id_producto': 'PROD1292',
'nombre': 'Nike Boots',
'precio': 172.06,
'marca': 'Nike',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 2.05},
{'id_producto': 'PROD1293',
'nombre': 'Nike Boots',
'precio': 94.25,
'marca': 'Nike',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 1.17},
{'id_producto': 'PROD1294',
'nombre': 'Nike Boots',
'precio': 283.46,
'marca': 'Nike',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 3.6},
{'id_producto': 'PROD1295',
'nombre': 'Nike Running Shoes',
'precio': 694.03,
'marca': 'Nike',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 3.36},
{'id_producto': 'PROD1296',
'nombre': 'Nike Slippers',
'precio': 246.59,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 4.76},
{'id_producto': 'PROD1297',
'nombre': 'Nike Sandals',
'precio': 796.13,
'marca': 'Nike',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 3.06},
{'id_producto': 'PROD1298',
'nombre': 'Adidas Boots',
'precio': 23.79,
'marca': 'Adidas',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 2.99},
{'id_producto': 'PROD1299',
'nombre': 'Adidas Running Shoes',
'precio': 149.37,
'marca': 'Adidas',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 1.68},
{'id_producto': 'PROD1300',
'nombre': 'Adidas Boots',
'precio': 503.27,
'marca': 'Adidas',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 3.9},
{'id_producto': 'PROD1301',
'nombre': 'Adidas Sneakers',
'precio': 447.01,
'marca': 'Adidas',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 3.04},
{'id_producto': 'PROD1302',
'nombre': 'Adidas Sneakers',
'precio': 238.8,
'marca': 'Adidas',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 1.49},
{'id_producto': 'PROD1303',
'nombre': 'Adidas Slippers',
'precio': 752.36,
'marca': 'Adidas',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 2.26},
{'id_producto': 'PROD1304',
'nombre': 'Adidas Running Shoes',
'precio': 890.46,
'marca': 'Adidas',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 1.06},
{'id_producto': 'PROD1305',
'nombre': 'Adidas Running Shoes',
'precio': 767.4,
'marca': 'Adidas',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 2.56},
{'id_producto': 'PROD1306',
'nombre': 'Reebok Slippers',
'precio': 760.98,
'marca': 'Reebok',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 2.3},
{'id_producto': 'PROD1307',
'nombre': 'Reebok Sneakers',
'precio': 339.36,
'marca': 'Reebok',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 1.29},
{'id_producto': 'PROD1308',
'nombre': 'Reebok Sneakers',
'precio': 371.89,
'marca': 'Reebok',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 4.23},
{'id_producto': 'PROD1309',
'nombre': 'Reebok Slippers',
'precio': 336.44,
'marca': 'Reebok',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 1.21},
{'id_producto': 'PROD1310',
'nombre': 'Reebok Boots',
'precio': 48.37,
'marca': 'Reebok',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 2.54},
{'id_producto': 'PROD1311',
'nombre': 'Reebok Slippers',
'precio': 18.52,
'marca': 'Reebok',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 3.06},
{'id_producto': 'PROD1312',
'nombre': 'Reebok Sneakers',
'precio': 52.57,
'marca': 'Reebok',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 1.98},
{'id_producto': 'PROD1313',
'nombre': 'Reebok Running Shoes',
'precio': 960.69,
'marca': 'Reebok',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 4.32},
{'id_producto': 'PROD1314',
'nombre': 'Reebok Slippers',
'precio': 280.16,
'marca': 'Reebok',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 2.77},
{'id_producto': 'PROD1315',
'nombre': 'Reebok Sneakers',
'precio': 246.9,
'marca': 'Reebok',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 4.8},
{'id_producto': 'PROD1316',
'nombre': 'Puma Slippers',
'precio': 148.65,
'marca': 'Puma',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 3.15},
{'id_producto': 'PROD1317',
'nombre': 'Puma Slippers',
'precio': 130.45,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 2.3},
{'id_producto': 'PROD1318',
'nombre': 'Puma Sneakers',
'precio': 961.45,
'marca': 'Puma',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 4.8},
{'id_producto': 'PROD1319',
'nombre': 'Puma Slippers',
'precio': 295.82,
'marca': 'Puma',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 3.06},
{'id_producto': 'PROD1320',
'nombre': 'Puma Boots',
'precio': 67.98,
'marca': 'Puma',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 2.98},
{'id_producto': 'PROD1321',
'nombre': 'Puma Slippers',
'precio': 22.52,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 2.87},
{'id_producto': 'PROD1322',
'nombre': 'Puma Slippers',
'precio': 944.93,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 2.69},
{'id_producto': 'PROD1323',
'nombre': 'Puma Slippers',
'precio': 304.63,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 2.38},
{'id_producto': 'PROD1324',
'nombre': 'Puma Sandals',
'precio': 794.04,
'marca': 'Puma',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 4.17},
{'id_producto': 'PROD1325',
'nombre': 'Puma Running Shoes',
'precio': 520.81,
'marca': 'Puma',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 1.34},
{'id_producto': 'PROD1326',
'nombre': 'Puma Sandals',
'precio': 57.19,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 2.16},
{'id_producto': 'PROD1327',
'nombre': 'Puma Boots',
'precio': 721.42,
'marca': 'Puma',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 4.35},
{'id_producto': 'PROD1328',
'nombre': 'Puma Running Shoes',
'precio': 293.83,
'marca': 'Puma',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 3.84},
{'id_producto': 'PROD1329',
'nombre': 'Skechers Running Shoes',
'precio': 584.31,
'marca': 'Skechers',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 2.82},
{'id_producto': 'PROD1330',
'nombre': 'Skechers Slippers',
'precio': 616.57,
'marca': 'Skechers',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 1.05},
{'id_producto': 'PROD1331',
'nombre': 'Skechers Boots',
'precio': 634.58,
'marca': 'Skechers',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 3.46},
{'id_producto': 'PROD1332',
'nombre': 'Skechers Sneakers',
'precio': 226.22,
'marca': 'Skechers',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 4.33},
{'id_producto': 'PROD1333',
'nombre': 'Skechers Sandals',
'precio': 319.93,
'marca': 'Skechers',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 2.78},
{'id_producto': 'PROD1334',
'nombre': 'Skechers Sneakers',
'precio': 161.14,
'marca': 'Skechers',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 1.38},
{'id_producto': 'PROD1335',
'nombre': 'Skechers Sandals',
'precio': 679.95,
'marca': 'Skechers',
'pais_fabricacion': 'Germany',
'categoria': 'Calzado',
'puntuacion_media': 4.63},
{'id_producto': 'PROD1336',
'nombre': 'Skechers Boots',
'precio': 974.87,
'marca': 'Skechers',
'pais_fabricacion': 'India',
'categoria': 'Calzado',
'puntuacion_media': 3.93},
{'id_producto': 'PROD1337',
'nombre': 'Skechers Boots',
'precio': 455.17,
'marca': 'Skechers',
'pais_fabricacion': 'Japan',
'categoria': 'Calzado',
'puntuacion_media': 1.27},
{'id_producto': 'PROD1338',
'nombre': 'Skechers Boots',
'precio': 497.4,
'marca': 'Skechers',
'pais_fabricacion': 'South Korea',
'categoria': 'Calzado',
'puntuacion_media': 2.41},
{'id_producto': 'PROD1339',
'nombre': 'Skechers Running Shoes',
'precio': 780.73,
'marca': 'Skechers',
'pais_fabricacion': 'USA',
'categoria': 'Calzado',
'puntuacion_media': 4.8},
{'id_producto': 'PROD1340',
'nombre': 'Skechers Sandals',
'precio': 870.67,
'marca': 'Skechers',
'pais_fabricacion': 'China',
'categoria': 'Calzado',
'puntuacion_media': 1.04},
{'id_producto': 'PROD1341',
'nombre': 'Dell Monitor',
'precio': 723.77,
'marca': 'Dell',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 1.69},
{'id_producto': 'PROD1342',
'nombre': 'Dell Mouse',
'precio': 959.37,
'marca': 'Dell',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 2.62},
{'id_producto': 'PROD1343',
'nombre': 'Dell Keyboard',
'precio': 196.94,
'marca': 'Dell',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 4.74},
{'id_producto': 'PROD1344',
'nombre': 'Dell Mouse',
'precio': 835.67,
'marca': 'Dell',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 3.4},
{'id_producto': 'PROD1345',
'nombre': 'Dell Keyboard',
'precio': 274.0,
'marca': 'Dell',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 3.32},
{'id_producto': 'PROD1346',
'nombre': 'Dell Laptop',
'precio': 211.71,
'marca': 'Dell',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 3.77},
{'id_producto': 'PROD1347',
'nombre': 'Dell Desktop',
'precio': 611.03,
'marca': 'Dell',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 2.3},
{'id_producto': 'PROD1348',
'nombre': 'Dell Monitor',
'precio': 924.41,
'marca': 'Dell',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 2.41},
{'id_producto': 'PROD1349',
'nombre': 'HP Desktop',
'precio': 926.72,
'marca': 'HP',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 1.67},
{'id_producto': 'PROD1350',
'nombre': 'HP Mouse',
'precio': 200.99,
'marca': 'HP',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 2.62},
{'id_producto': 'PROD1351',
'nombre': 'HP Monitor',
'precio': 64.79,
'marca': 'HP',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 3.34},
{'id_producto': 'PROD1352',
'nombre': 'HP Monitor',
'precio': 239.12,
'marca': 'HP',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 1.04},
{'id_producto': 'PROD1353',
'nombre': 'HP Mouse',
'precio': 985.19,
'marca': 'HP',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 3.6},
{'id_producto': 'PROD1354',
'nombre': 'HP Monitor',
'precio': 901.85,
'marca': 'HP',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 1.03},
{'id_producto': 'PROD1355',
'nombre': 'HP Laptop',
'precio': 331.71,
'marca': 'HP',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 3.69},
{'id_producto': 'PROD1356',
'nombre': 'HP Laptop',
'precio': 448.95,
'marca': 'HP',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 3.36},
{'id_producto': 'PROD1357',
'nombre': 'HP Laptop',
'precio': 201.54,
'marca': 'HP',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 4.81},
{'id_producto': 'PROD1358',
'nombre': 'HP Monitor',
'precio': 211.54,
'marca': 'HP',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 1.53},
{'id_producto': 'PROD1359',
'nombre': 'HP Laptop',
'precio': 47.69,
'marca': 'HP',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 4.41},
{'id_producto': 'PROD1360',
'nombre': 'HP Keyboard',
'precio': 706.52,
'marca': 'HP',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 4.64},
{'id_producto': 'PROD1361',
'nombre': 'Apple Mouse',
'precio': 349.55,
'marca': 'Apple',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 3.23},
{'id_producto': 'PROD1362',
'nombre': 'Apple Keyboard',
'precio': 595.86,
'marca': 'Apple',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 4.66},
{'id_producto': 'PROD1363',
'nombre': 'Apple Desktop',
'precio': 246.28,
'marca': 'Apple',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 2.05},
{'id_producto': 'PROD1364',
'nombre': 'Apple Laptop',
'precio': 668.94,
'marca': 'Apple',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 3.77},
{'id_producto': 'PROD1365',
'nombre': 'Apple Laptop',
'precio': 712.99,
'marca': 'Apple',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 2.19},
{'id_producto': 'PROD1366',
'nombre': 'Apple Laptop',
'precio': 156.34,
'marca': 'Apple',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 2.76},
{'id_producto': 'PROD1367',
'nombre': 'Apple Laptop',
'precio': 895.96,
'marca': 'Apple',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 3.58},
{'id_producto': 'PROD1368',
'nombre': 'Apple Keyboard',
'precio': 540.51,
'marca': 'Apple',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 2.41},
{'id_producto': 'PROD1369',
'nombre': 'Apple Desktop',
'precio': 650.67,
'marca': 'Apple',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 1.04},
{'id_producto': 'PROD1370',
'nombre': 'Apple Laptop',
'precio': 382.48,
'marca': 'Apple',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 4.17},
{'id_producto': 'PROD1371',
'nombre': 'Asus Keyboard',
'precio': 157.05,
'marca': 'Asus',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 1.13},
{'id_producto': 'PROD1372',
'nombre': 'Asus Mouse',
'precio': 377.29,
'marca': 'Asus',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 4.89},
{'id_producto': 'PROD1373',
'nombre': 'Asus Mouse',
'precio': 302.41,
'marca': 'Asus',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 4.37},
{'id_producto': 'PROD1374',
'nombre': 'Asus Monitor',
'precio': 83.05,
'marca': 'Asus',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 3.09},
{'id_producto': 'PROD1375',
'nombre': 'Asus Mouse',
'precio': 200.91,
'marca': 'Asus',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 4.88},
{'id_producto': 'PROD1376',
'nombre': 'Asus Monitor',
'precio': 357.04,
'marca': 'Asus',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 3.22},
{'id_producto': 'PROD1377',
'nombre': 'Asus Laptop',
'precio': 887.36,
'marca': 'Asus',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 2.69},
{'id_producto': 'PROD1378',
'nombre': 'Asus Mouse',
'precio': 338.68,
'marca': 'Asus',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 2.86},
{'id_producto': 'PROD1379',
'nombre': 'Asus Keyboard',
'precio': 274.52,
'marca': 'Asus',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 1.45},
{'id_producto': 'PROD1380',
'nombre': 'Asus Monitor',
'precio': 262.88,
'marca': 'Asus',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 2.35},
{'id_producto': 'PROD1381',
'nombre': 'Asus Laptop',
'precio': 627.96,
'marca': 'Asus',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 3.83},
{'id_producto': 'PROD1382',
'nombre': 'Asus Desktop',
'precio': 53.6,
'marca': 'Asus',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 3.2},
{'id_producto': 'PROD1383',
'nombre': 'Acer Keyboard',
'precio': 425.26,
'marca': 'Acer',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 3.46},
{'id_producto': 'PROD1384',
'nombre': 'Acer Mouse',
'precio': 205.58,
'marca': 'Acer',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 4.92},
{'id_producto': 'PROD1385',
'nombre': 'Acer Mouse',
'precio': 852.96,
'marca': 'Acer',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 4.08},
{'id_producto': 'PROD1386',
'nombre': 'Acer Monitor',
'precio': 544.73,
'marca': 'Acer',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 2.61},
{'id_producto': 'PROD1387',
'nombre': 'Acer Desktop',
'precio': 538.38,
'marca': 'Acer',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 3.47},
{'id_producto': 'PROD1388',
'nombre': 'Acer Desktop',
'precio': 733.65,
'marca': 'Acer',
'pais_fabricacion': 'Germany',
'categoria': 'Computadoras',
'puntuacion_media': 1.21},
{'id_producto': 'PROD1389',
'nombre': 'Acer Monitor',
'precio': 602.23,
'marca': 'Acer',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 2.15},
{'id_producto': 'PROD1390',
'nombre': 'Acer Laptop',
'precio': 707.69,
'marca': 'Acer',
'pais_fabricacion': 'USA',
'categoria': 'Computadoras',
'puntuacion_media': 1.72},
{'id_producto': 'PROD1391',
'nombre': 'Acer Laptop',
'precio': 35.29,
'marca': 'Acer',
'pais_fabricacion': 'Japan',
'categoria': 'Computadoras',
'puntuacion_media': 2.61},
{'id_producto': 'PROD1392',
'nombre': 'Acer Laptop',
'precio': 851.83,
'marca': 'Acer',
'pais_fabricacion': 'India',
'categoria': 'Computadoras',
'puntuacion_media': 3.91},
{'id_producto': 'PROD1393',
'nombre': 'Acer Desktop',
'precio': 106.1,
'marca': 'Acer',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 3.42},
{'id_producto': 'PROD1394',
'nombre': 'Acer Laptop',
'precio': 733.11,
'marca': 'Acer',
'pais_fabricacion': 'South Korea',
'categoria': 'Computadoras',
'puntuacion_media': 3.31},
{'id_producto': 'PROD1395',
'nombre': 'Acer Desktop',
'precio': 454.33,
'marca': 'Acer',
'pais_fabricacion': 'China',
'categoria': 'Computadoras',
'puntuacion_media': 3.35}]);